package cmd

var resources = map[string]string{
	"A4B":                        "",
	"ACM":                        "aws_acm_certificate",
	"AWSAmplify":                 "aws_amplify_app",
	"AWSAppFabric":               "",
	"AWSAppRunner":               "aws_apprunner_service",
	"AWSAppStudio":               "",
	"AWSAppSync":                 "aws_appsync_graphql_api",
	"AWSApplicationMigrationSvc": "",
	"AWSB2Bi":                    "",
	"AWSBCMPricingCalculator":    "",
	"AWSBackup":                  "aws_backup_vault",
	"AWSBillingConductor":        "",
	"AWSCertificateManager":      "aws_acm_certificate",
	"AWSCleanRooms":              "",
	"AWSCloudFormation":          "aws_cloudformation_stack",
	"AWSCloudMap":                "aws_service_discovery_service",
	"AWSCloudTrail":              "aws_cloudtrail",
	"AWSCloudWAN":                "",
	"AWSCodeArtifact":            "aws_codeartifact_repository",
	"AWSCodeDeploy":              "aws_codedeploy_deployment_group",
	"AWSCodePipeline":            "aws_codepipeline",
	"AWSComputeOptimizer":        "",
	"AWSConfig":                  "aws_config_configuration_recorder",
	"AmazonEC2":                  "aws_instance",
	"AmazonRDS":                  "aws_db_instance",
}
